coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "modules/conformance/**/*"
  - "**/benchmark/**/*"
  - "**/target/**/*"
  - "project/**/*"
