package io.forge.jam.pvm.program

/**
 * Represents a virtual machine instruction.
 * Each variant contains the instruction type and its associated parameters.
 */
sealed class Instruction {
    data object Trap : Instruction()
    data object Fallthrough : Instruction()
    data class JumpIndirect(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadImm(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadU8(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadI8(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadU16(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadI16(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadU32(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadI32(val reg: RawReg, val imm: UInt) : Instruction()
    data class LoadU64(val reg: RawReg, val imm: UInt) : Instruction()
    data class StoreU8(val reg: RawReg, val imm: UInt) : Instruction()
    data class StoreU16(val reg: RawReg, val imm: UInt) : Instruction()
    data class StoreU32(val reg: RawReg, val imm: UInt) : Instruction()
    data class StoreU64(val reg: RawReg, val imm: UInt) : Instruction()

    data class LoadImmAndJump(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchEqImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchNotEqImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchLessUnsignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchLessSignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchGreaterOrEqualUnsignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchGreaterOrEqualSignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchLessOrEqualSignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchLessOrEqualUnsignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchGreaterSignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class BranchGreaterUnsignedImm(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()

    data class StoreImmIndirectU8(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmIndirectU16(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmIndirectU32(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmIndirectU64(val reg: RawReg, val imm1: UInt, val imm2: UInt) : Instruction()

    data class StoreIndirectU8(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class StoreIndirectU16(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class StoreIndirectU32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class StoreIndirectU64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectU8(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectI8(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectU16(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectI16(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectI32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectU32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class LoadIndirectU64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class AddImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class AddImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class AndImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class XorImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class OrImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class MulImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class MulImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class SetLessThanUnsignedImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class SetLessThanSignedImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalLeftImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalLeftImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalRightImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalRightImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftArithmeticRightImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftArithmeticRightImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class NegateAndAddImm32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class NegateAndAddImm64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class SetGreaterThanUnsignedImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class SetGreaterThanSignedImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalRightImmAlt32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalRightImmAlt64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftArithmeticRightImmAlt32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftArithmeticRightImmAlt64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalLeftImmAlt32(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class ShiftLogicalLeftImmAlt64(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class CmovIfZeroImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class CmovIfNotZeroImm(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchEq(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchNotEq(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchLessUnsigned(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchLessSigned(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchGreaterOrEqualUnsigned(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class BranchGreaterOrEqualSigned(val reg1: RawReg, val reg2: RawReg, val imm: UInt) : Instruction()
    data class Add32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Add64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Sub32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Sub64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class And(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Xor(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Or(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Mul32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Mul64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class MulUpperSignedSigned(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class MulUpperUnsignedUnsigned(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class MulUpperSignedUnsigned(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class SetLessThanUnsigned(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class SetLessThanSigned(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftLogicalLeft32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftLogicalLeft64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftLogicalRight32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftLogicalRight64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftArithmeticRight32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class ShiftArithmeticRight64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class DivUnsigned32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class DivUnsigned64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class DivSigned32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class DivSigned64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class RemUnsigned32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class RemUnsigned64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class RemSigned32(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class RemSigned64(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class CmovIfZero(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class CmovIfNotZero(val reg1: RawReg, val reg2: RawReg, val reg3: RawReg) : Instruction()
    data class Jump(val imm: UInt) : Instruction()
    data class Ecalli(val imm: UInt) : Instruction()
    data class StoreImmU8(val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmU16(val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmU32(val imm1: UInt, val imm2: UInt) : Instruction()
    data class StoreImmU64(val imm1: UInt, val imm2: UInt) : Instruction()
    data class MoveReg(val reg1: RawReg, val reg2: RawReg) : Instruction()
    data class Sbrk(val reg1: RawReg, val reg2: RawReg) : Instruction()
    data class LoadImmAndJumpIndirect(val reg1: RawReg, val reg2: RawReg, val imm1: UInt, val imm2: UInt) :
        Instruction()

    data class LoadImm64(val reg: RawReg, val imm: ULong) : Instruction()
    data object Invalid : Instruction()

    /**
     * Visits the instruction with a visitor implementation
     */
    fun <T> visit(visitor: InstructionVisitor<T>): T = when (this) {
        is Trap -> visitor.trap()
        is Fallthrough -> visitor.fallthrough()
        is JumpIndirect -> visitor.jumpIndirect(reg, imm)
        is LoadImm -> visitor.loadImm(reg, imm)
        is LoadU8 -> visitor.loadU8(reg, imm)
        is LoadI8 -> visitor.loadI8(reg, imm)
        is LoadU16 -> visitor.loadU16(reg, imm)
        is LoadI16 -> visitor.loadI16(reg, imm)
        is LoadU32 -> visitor.loadU32(reg, imm)
        is LoadI32 -> visitor.loadI32(reg, imm)
        is LoadU64 -> visitor.loadU64(reg, imm)
        is StoreU8 -> visitor.storeU8(reg, imm)
        is StoreU16 -> visitor.storeU16(reg, imm)
        is StoreU32 -> visitor.storeU32(reg, imm)
        is StoreU64 -> visitor.storeU64(reg, imm)
        is LoadImmAndJump -> visitor.loadImmAndJump(reg, imm1, imm2)
        is BranchEqImm -> visitor.branchEqImm(reg, imm1, imm2)
        is BranchNotEqImm -> visitor.branchNotEqImm(reg, imm1, imm2)
        is BranchLessUnsignedImm -> visitor.branchLessUnsignedImm(reg, imm1, imm2)
        is BranchLessSignedImm -> visitor.branchLessSignedImm(reg, imm1, imm2)
        is BranchGreaterOrEqualUnsignedImm -> visitor.branchGreaterOrEqualUnsignedImm(reg, imm1, imm2)
        is BranchGreaterOrEqualSignedImm -> visitor.branchGreaterOrEqualSignedImm(reg, imm1, imm2)
        is BranchLessOrEqualSignedImm -> visitor.branchLessOrEqualSignedImm(reg, imm1, imm2)
        is BranchLessOrEqualUnsignedImm -> visitor.branchLessOrEqualUnsignedImm(reg, imm1, imm2)
        is BranchGreaterSignedImm -> visitor.branchGreaterSignedImm(reg, imm1, imm2)
        is BranchGreaterUnsignedImm -> visitor.branchGreaterUnsignedImm(reg, imm1, imm2)
        is StoreImmIndirectU8 -> visitor.storeImmIndirectU8(reg, imm1, imm2)
        is StoreImmIndirectU16 -> visitor.storeImmIndirectU16(reg, imm1, imm2)
        is StoreImmIndirectU32 -> visitor.storeImmIndirectU32(reg, imm1, imm2)
        is StoreImmIndirectU64 -> visitor.storeImmIndirectU64(reg, imm1, imm2)
        is StoreIndirectU8 -> visitor.storeIndirectU8(reg1, reg2, imm)
        is StoreIndirectU16 -> visitor.storeIndirectU16(reg1, reg2, imm)
        is StoreIndirectU32 -> visitor.storeIndirectU32(reg1, reg2, imm)
        is StoreIndirectU64 -> visitor.storeIndirectU64(reg1, reg2, imm)
        is LoadIndirectU8 -> visitor.loadIndirectU8(reg1, reg2, imm)
        is LoadIndirectI8 -> visitor.loadIndirectI8(reg1, reg2, imm)
        is LoadIndirectU16 -> visitor.loadIndirectU16(reg1, reg2, imm)
        is LoadIndirectI16 -> visitor.loadIndirectI16(reg1, reg2, imm)
        is LoadIndirectI32 -> visitor.loadIndirectI32(reg1, reg2, imm)
        is LoadIndirectU32 -> visitor.loadIndirectU32(reg1, reg2, imm)
        is LoadIndirectU64 -> visitor.loadIndirectU64(reg1, reg2, imm)
        is AddImm32 -> visitor.addImm32(reg1, reg2, imm)
        is AddImm64 -> visitor.addImm64(reg1, reg2, imm)
        is AndImm -> visitor.andImm(reg1, reg2, imm)
        is XorImm -> visitor.xorImm(reg1, reg2, imm)
        is OrImm -> visitor.orImm(reg1, reg2, imm)
        is MulImm32 -> visitor.mulImm32(reg1, reg2, imm)
        is MulImm64 -> visitor.mulImm64(reg1, reg2, imm)
        is MulUpperSignedSigned -> visitor.mulUpperSignedSigned(reg1, reg2, reg3)
        is MulUpperSignedUnsigned -> visitor.mulUpperSignedUnsigned(reg1, reg2, reg3)
        is MulUpperUnsignedUnsigned -> visitor.mulUpperUnsignedUnsigned(reg1, reg2, reg3)
        is SetLessThanUnsignedImm -> visitor.setLessThanUnsignedImm(reg1, reg2, imm)
        is SetLessThanSignedImm -> visitor.setLessThanSignedImm(reg1, reg2, imm)
        is ShiftLogicalLeft32 -> visitor.shiftLogicalLeft32(reg1, reg2, reg3)
        is ShiftLogicalLeft64 -> visitor.shiftLogicalLeft64(reg1, reg2, reg3)
        is ShiftLogicalRight32 -> visitor.shiftLogicalRight32(reg1, reg2, reg3)
        is ShiftLogicalRight64 -> visitor.shiftLogicalRight64(reg1, reg2, reg3)
        is ShiftArithmeticRight32 -> visitor.shiftArithmeticRight32(reg1, reg2, reg3)
        is ShiftArithmeticRight64 -> visitor.shiftArithmeticRight64(reg1, reg2, reg3)
        is NegateAndAddImm32 -> visitor.negateAndAddImm32(reg1, reg2, imm)
        is NegateAndAddImm64 -> visitor.negateAndAddImm64(reg1, reg2, imm)
        is SetGreaterThanUnsignedImm -> visitor.setGreaterThanUnsignedImm(reg1, reg2, imm)
        is SetGreaterThanSignedImm -> visitor.setGreaterThanSignedImm(reg1, reg2, imm)
        is ShiftLogicalRightImmAlt32 -> visitor.shiftLogicalRightImmAlt32(reg1, reg2, imm)
        is ShiftLogicalRightImmAlt64 -> visitor.shiftLogicalRightImmAlt64(reg1, reg2, imm)
        is ShiftArithmeticRightImmAlt32 -> visitor.shiftArithmeticRightImmAlt32(reg1, reg2, imm)
        is ShiftArithmeticRightImmAlt64 -> visitor.shiftArithmeticRightImmAlt64(reg1, reg2, imm)
        is ShiftLogicalLeftImmAlt32 -> visitor.shiftLogicalLeftImmAlt32(reg1, reg2, imm)
        is ShiftLogicalLeftImmAlt64 -> visitor.shiftLogicalLeftImmAlt64(reg1, reg2, imm)
        is CmovIfZeroImm -> visitor.cmovIfZeroImm(reg1, reg2, imm)
        is CmovIfNotZeroImm -> visitor.cmovIfNotZeroImm(reg1, reg2, imm)
        is BranchEq -> visitor.branchEq(reg1, reg2, imm)
        is BranchNotEq -> visitor.branchNotEq(reg1, reg2, imm)
        is BranchLessUnsigned -> visitor.branchLessUnsigned(reg1, reg2, imm)
        is BranchLessSigned -> visitor.branchLessSigned(reg1, reg2, imm)
        is BranchGreaterOrEqualUnsigned -> visitor.branchGreaterOrEqualUnsigned(reg1, reg2, imm)
        is BranchGreaterOrEqualSigned -> visitor.branchGreaterOrEqualSigned(reg1, reg2, imm)
        is Add32 -> visitor.add32(reg1, reg2, reg3)
        is Add64 -> visitor.add64(reg1, reg2, reg3)
        is Sub32 -> visitor.sub32(reg1, reg2, reg3)
        is Sub64 -> visitor.sub64(reg1, reg2, reg3)
        is And -> visitor.and(reg1, reg2, reg3)
        is Xor -> visitor.xor(reg1, reg2, reg3)
        is Or -> visitor.or(reg1, reg2, reg3)
        is Mul32 -> visitor.mul32(reg1, reg2, reg3)
        is Mul64 -> visitor.mul64(reg1, reg2, reg3)
        is SetLessThanUnsigned -> visitor.setLessThanUnsigned(reg1, reg2, reg3)
        is SetLessThanSigned -> visitor.setLessThanSigned(reg1, reg2, reg3)
        is DivUnsigned32 -> visitor.divUnsigned32(reg1, reg2, reg3)
        is DivUnsigned64 -> visitor.divUnsigned64(reg1, reg2, reg3)
        is DivSigned32 -> visitor.divSigned32(reg1, reg2, reg3)
        is DivSigned64 -> visitor.divSigned64(reg1, reg2, reg3)
        is RemUnsigned32 -> visitor.remUnsigned32(reg1, reg2, reg3)
        is RemUnsigned64 -> visitor.remUnsigned64(reg1, reg2, reg3)
        is RemSigned32 -> visitor.remSigned32(reg1, reg2, reg3)
        is RemSigned64 -> visitor.remSigned64(reg1, reg2, reg3)
        is CmovIfZero -> visitor.cmovIfZero(reg1, reg2, reg3)
        is CmovIfNotZero -> visitor.cmovIfNotZero(reg1, reg2, reg3)
        is Jump -> visitor.jump(imm)
        is Ecalli -> visitor.ecalli(imm)
        is StoreImmU8 -> visitor.storeImmU8(imm1, imm2)
        is StoreImmU16 -> visitor.storeImmU16(imm1, imm2)
        is StoreImmU32 -> visitor.storeImmU32(imm1, imm2)
        is StoreImmU64 -> visitor.storeImmU64(imm1, imm2)
        is MoveReg -> visitor.moveReg(reg1, reg2)
        is Sbrk -> visitor.sbrk(reg1, reg2)
        is LoadImmAndJumpIndirect -> visitor.loadImmAndJumpIndirect(reg1, reg2, imm1, imm2)
        is Invalid -> visitor.invalid()
        is ShiftArithmeticRightImm32 -> visitor.shiftArithmeticRightImm32(reg1, reg2, imm)
        is ShiftArithmeticRightImm64 -> visitor.shiftArithmeticRightImm64(reg1, reg2, imm)
        is ShiftLogicalLeftImm32 -> visitor.shiftLogicalLeftImm32(reg1, reg2, imm)
        is ShiftLogicalLeftImm64 -> visitor.shiftLogicalLeftImm64(reg1, reg2, imm)
        is ShiftLogicalRightImm32 -> visitor.shiftLogicalRightImm32(reg1, reg2, imm)
        is ShiftLogicalRightImm64 -> visitor.shiftLogicalRightImm64(reg1, reg2, imm)
        is LoadImm64 -> visitor.loadImm64(reg, imm)
    }

    /**
     * Gets the opcode for this instruction
     */
    fun opcode(): Opcode = when (this) {
        is Trap -> Opcode.trap
        is Fallthrough -> Opcode.fallthrough
        is Invalid -> Opcode.trap
        is JumpIndirect -> Opcode.jump_indirect
        is LoadImm -> Opcode.load_imm
        is LoadU8 -> Opcode.load_u8
    }

    /**
     * Serializes the instruction into a byte buffer
     */
    fun serializeInto(position: UInt, buffer: ByteArray): Int {
        TODO("Implementation needed")
    }

    companion object {
        /**
         * Serialization helper methods would go here
         */
        private fun serializeArgless(buffer: ByteArray, opcode: Opcode): Int {
            TODO("Implementation needed")
        }

        private fun serializeRegImm(buffer: ByteArray, opcode: Opcode, reg: RawReg, imm: UInt): Int {
            TODO("Implementation needed")
        }
    }
}
